//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakanlıkProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakanlık
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bakanlık()
        {
            this.Vergilers = new HashSet<Vergiler>();
        }
    
        public int bakanlıkID { get; set; }
        public string bakanlıkAdi { get; set; }
        public string daireBaskanlik { get; set; }
        public Nullable<decimal> Ciro { get; set; }
        public string Merkez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vergiler> Vergilers { get; set; }
    }
}
