//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakanlıkProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vatanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vatanda()
        {
            this.Vergilers = new HashSet<Vergiler>();
        }
    
        public int vatandasID { get; set; }
        public string TCNo { get; set; }
        public string Meslek { get; set; }
        public string Adres { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vergiler> Vergilers { get; set; }
    }
}
