//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakanlıkProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vergiler
    {
        public int vergiID { get; set; }
        public string vergiAdi { get; set; }
        public string vergiTipi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string faiz { get; set; }
        public Nullable<int> bakanlıkID { get; set; }
        public Nullable<int> vatandasID { get; set; }
    
        public virtual Bakanlık Bakanlık { get; set; }
        public virtual Vatanda Vatanda { get; set; }
    }
}
